# Python Basic Tutorial 

print("Hola mundo")

B : new lines

DD : drop lines 

shift: select many lines

run : ctr + enter 

# Libraries

A library is a collection of modules or a single module. Modules are python programs that can be imported in another Python program. Libraries are the tools we will use to make our program.

Some special libraries such import $TensorFlow, Keras, Geopandas$ requiere of using Conda Promtp. We back this issue later. 


\begin{equation}
    u_i
\end{equation}

In [265]:
# libraies t use date base and arrays
import pandas as pd
import numpy as np

np.DataFrame
sb.hexibn (c, y)

### Python Types

There are three key python types: int, float, string and boolean.

In [269]:
# Int type
edad = 25
edad

type(edad)

int

In [270]:
# Float type
precio = 19.99
type(precio)


float

In [14]:
numero_complejo = 3 + 4j  # Parte real + parte imaginaria
numero_complejo
type(numero_complejo)

complex

In [271]:
#String type
mensaje = "Hola, mundo!"

type(mensaje)

str

In [272]:
mensaje[0]

'H'

In [274]:
print(mensaje[0], ";", mensaje[0:6])

H ; Hola, 


In [19]:
# Boolean variables
a = True  
b = False  

print(type(a), '\n', type(b))



<class 'bool'> 
 <class 'bool'>


In [275]:
"a" == "a"

True

In [160]:
print("a" != "b")  # True, because "a" and "b" are different
print("a" != "a")  # False, because "a" and "a" are the same


True
False


In [276]:
z1 = (10 < 20)

z2 = (1==1)

#z1

print(z2,'\n', z1)
#int(z1)

True 
 True


## 3.0 Tuple

#### It is an ordered and immutable Python object

In [284]:
coordenadas = (10, 20, 30)
#coordenadas[0] = 50  #  Error: 'tuple' object does not support item assignment
coordenadas

(10, 20, 30)

In [282]:
T1 = (1,4,8,10,20,15,4,5,8,8)

print(type(T1))


print("Suma:", sum(T1),'\n', "Minimo:", min(T1), '\n', "Maximo:", max(T1))

<class 'tuple'>
Suma: 83 
 Minimo: 1 
 Maximo: 20


In [167]:
print("Sum:", sum(T1), '\n',  
      "Minimum:", min(T1), '\n',  
      "Maximum:", max(T1), '\n',  
      "Average:", sum(T1) / len(T1))


Sum: 83 
 Minimum: 1 
 Maximum: 20 
 Average: 8.3


In [168]:
T1[4]

20

In [170]:
T1[1:9] # let us for selecting from 0 to before 4 [0-3]

(4, 8, 10, 20, 15, 4, 5, 8)

# 4.0 List

#### It is an ordered and mutable Python container.

In [35]:
# Empty List

L1 = []

type(L1)

list

In [286]:
a = [3,4,5,"ATE", 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO']
type(a)
print(a)

a[0:2]

[3, 4, 5, 'ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO']


[3, 4]

In [287]:
#a.append(["San Miguel", "La marina"])
a.append(["COMAS"])

print(a)

[3, 4, 5, 'ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', ['COMAS']]


### Indexing
Selecting elements starting from 0. I know it sounds crazy. 
Selecting takes one position before the last requested column

In [47]:
print('first element:',a[0])
print(a[1:4]) # takes element position 1° to 3°, NOT 4°
print('first 5 element:',a[0:5]) # 0,1,2,3,4 

first element: 3
[4, 5, 'ATE']
first 5 element: [3, 4, 5, 'ATE', 'BARRANCO']


In [53]:
# use next line to complete list
b = ['ATE', 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO','CHACLACAYO','CHORRILLOS','CIENEGUILLA'
     ,'COMAS','EL_AGUSTINO','INDEPENDENCIA']

In [49]:
# last elements 
print(b[-1])

INDEPENDENCIA


In [52]:
print(b[-3:]) #end

['COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA']


In [55]:
len(b) # Amount

11

In [288]:
# add elements to list
num = [10,20,30]
b.extend(num)
print(b)
len(b)

['ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA', 10, 20, 30, 10, 20, 30]


17

# Dictionaries - THE WITCH
It is a unordered and mutable Python container.

In [57]:
# dictionary containing the population of the 5 largest german cities
population = {'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 }
population.keys()


# enaho.rename( column, {var : ingreso_hora})

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt'])

In [14]:
population['Hamburg']

1822445

In [58]:
population_18_19 = {'Berlin': [3748148, 38000, "alex"], 'Hamburg': [1822445, 1922445], 
                    'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 , 'lima': 1100000}

In [59]:
population_18_19['Berlin']

[3748148, 38000, 'alex']

In [60]:
pop_germnay = population_18_19["Berlin"][0] + population_18_19["Munich"] + population_18_19["Hamburg"][0]+ population_18_19["Frankfurt"]
pop_germnay

7795157

# Array (vectors and matrix)

### [Key Methods](https://cs231n.github.io/python-numpy-tutorial/)

| Method | Description |
| -------- | ------------ |
|dtype  | type of elements in the array|
|ndim   |  dimension of array|
|shape  |  tuple with the dimmension of the array|
|size |  total number of elements in the array|

In [62]:
import numpy as np

In [63]:
a = np.array( [1, 2, 3, 4, 5] )
a
type(a)

numpy.ndarray

In [71]:
c1 = np.array([3,4,5,6,6])
c1

array([3, 4, 5, 6, 6])

In [295]:
a = np.array([1,2,3,4,5])
#a = [1,2,3,4,5]
#a.size 
len(a) 

5

In [296]:
print(a.size)
print(a.shape)
print(a.ndim)

len(a)

5
(5,)
1


5

In [77]:
# 2D array
M = np.array( [ [3, 4, 2], [1, 2, 6] ] )
print(M)

M1 = np.nan
M1
print("n° elements:", M.size, '\n', "rows and columns:", M.shape, '\n', "n° dimension:", M.ndim)

[[3 4 2]
 [1 2 6]]
n° elements: 6 
 rows and columns: (2, 3) 
 n° dimension: 2


### ***[Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)***


|Function|Return|
| --- | --- |
|arange( )|array of sequence|
|eye( )|diagonal array|
|ones( )|array of ones|
|zeros( )|array of zeros|

In [297]:
peru = np.arange(start = 1,stop = 13,step = 5)
print(peru)
type(peru)

[ 1  6 11]


numpy.ndarray

In [298]:
y = np.arange(1,11)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [299]:
y = np.arange( 0, 20, 5 )
print(y)
print(y[0:3])

[ 0  5 10 15]
[ 0  5 10]


In [82]:
y1 = np.arange( 1, 10 ) # one step 
y1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a4 = np.ones(10)
print(a4, '\n')
a5 = np.ones((10,10))
print(a5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [84]:
a6 = np.zeros(5)
print(a6,'\n')
a7 = np.zeros((10,10))
print(a7)

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [85]:
a8 = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])
a8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [301]:
a8[2:5,:]  # rows selection
#a8[2:5]  # rows selection

array([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [31]:
a8[:,0:6]  # columns selecrtion

array([[  0,   1,   2,   3,   4,   5],
       [ 10,  11,  12,  13,  14,  15],
       [ 30,  31,  32,  33,  34,  35],
       [-20, -19, -18, -17, -16, -15],
       [  2,   4,   6,   8,  10,  12]])

### ***[Array Manipulation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)***

In [87]:
# Reshape

w = np.arange(0,24)
print( w )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [90]:
print(w.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [89]:
print(w.reshape(24,1))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [91]:
print(w.reshape(2,12))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [94]:
M1 = np.zeros( (8, 2) )
M2 = np.ones( (8, 4) )
print(M1,"\n","\n", M2)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 
 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [95]:
M3 = np.hstack((M1,M2))  # add columns in horizontal way
M3

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

## Axis

### axis = 0 : vertical operation
### axis = 1 : horizontal operation

In [102]:
con1 = np.concatenate((M1,M2), axis = 1) # add more columns. This is a horizontal operation
con1

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [103]:
# Transpose
mat_3 = M3.T
print("mat5 \n" , mat_3)

mat5 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [106]:
M4 = np.array([[2,2,3,4,5,1],[1,5,5,9,8,2]])
M4.shape
print(M4)

[[2 2 3 4 5 1]
 [1 5 5 9 8 2]]


In [107]:
M5 = np.vstack((M3,M4))  # add columns in horizontal way
M5

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [2., 2., 3., 4., 5., 1.],
       [1., 5., 5., 9., 8., 2.]])

In [108]:
con2 = np.concatenate((M3,M4), axis = 0) # add more rows. This is a vertical operation
con2

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [2., 2., 3., 4., 5., 1.],
       [1., 5., 5., 9., 8., 2.]])

In [42]:

mat_5 = M5.T
print("mat4 \n" , mat_5)

mat4 
 [[0. 0. 0. 0. 0. 0. 0. 0. 2. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 5.]
 [1. 1. 1. 1. 1. 1. 1. 1. 3. 5.]
 [1. 1. 1. 1. 1. 1. 1. 1. 4. 9.]
 [1. 1. 1. 1. 1. 1. 1. 1. 5. 8.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]]


# [Pandas](https://pandas.pydata.org/docs/user_guide/index.html)
It helps us to store data in a 2-dimensional labeled data structure with columns of potentially different types.

In [113]:
import pandas as pd

In [171]:
# crear lists
students = ["Alejandro","Pedro","Ramiro","Axel","Juan"]
math = [15,16,10,12,13]
english = [13,9,16,14,17]
art = [12,16,15,19,10]

# Make a dictionary
grades = {"Students": students, "Math":math, "English":english, "Art":art}
grades

{'Students': ['Alejandro', 'Pedro', 'Ramiro', 'Axel', 'Juan'],
 'Math': [15, 16, 10, 12, 13],
 'English': [13, 9, 16, 14, 17],
 'Art': [12, 16, 15, 19, 10]}

In [115]:
data1 = pd.DataFrame(grades)
data1

Students  Math  English  Art
0  Alejandro    15       13   12
1      Pedro    16        9   16
2     Ramiro    10       16   15
3       Axel    12       14   19
4       Juan    13       17   10

In [116]:
# Change columns names
dic1 = { "Students":'St', "Math":'Ma', "English":'En', "Art":'Ar'} # dictionary
data1.rename( columns = dic1)

St  Ma  En  Ar
0  Alejandro  15  13  12
1      Pedro  16   9  16
2     Ramiro  10  16  15
3       Axel  12  14  19
4       Juan  13  17  10

In [172]:
data1.rename( columns = { "Students":'St', "Math":'Ma', "English":'En', "Art":'Ar'}  )

St  Ma  En  Ar
0  Alejandro  15  13  12
1      Pedro  16   9  16
2     Ramiro  10  16  15
3       Axel  12  14  19
4       Juan  13  17  10

In [173]:
# Add column and index row name
data = {'state': ['Lima', 'Piura', 'Tumbes', 'Cuzco', 'Ica', 'Puno'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [174]:
frame = pd.DataFrame(data, 
                      columns=["year", 'state', 'pop', 'debt'] ,
                      index=['one', 'two', 'three', 'four','five', 'six'] )

frame

year   state  pop debt
one    2000    Lima  1.5  NaN
two    2001   Piura  1.7  NaN
three  2002  Tumbes  3.6  NaN
four   2001   Cuzco  2.4  NaN
five   2002     Ica  2.9  NaN
six    2003    Puno  3.2  NaN

# Load  files : CSV, Excel

In [124]:
import os
import os
print(os.getcwd())  # Muestra la carpeta actual


C:\Users\melor\OneDrive\Documentos\GitHub\Python for Data Science


In [182]:
#using relative path
#import pandas as pd
#r'..\data\base1.xlsx'
base0 = pd.read_excel(r'./data/base1.xlsx', sheet_name = "data")

print(type(base0))
base0.head()

#base0.to_csv(r'./data/base.csv')

<class 'pandas.core.frame.DataFrame'>


Unnamed: 0       wage     lwage  sex  shs  hsg  scl  clg  ad  mw  ...  we  \
0          10   9.615385  2.263364    1    0    0    0    1   0   0  ...   0   
1          12  48.076923  3.872802    0    0    0    0    1   0   0  ...   0   
2          15  11.057692  2.403126    0    0    1    0    0   0   0  ...   0   
3          18  13.942308  2.634928    1    0    0    0    0   1   0  ...   0   
4          19  28.846154  3.361977    1    0    0    0    1   0   0  ...   0   

   ne  exp1  exp2    exp3     exp4   occ  occ2   ind  ind2  
0   1   7.0  0.49   0.343   0.2401  3600    11  8370    18  
1   1  31.0  9.61  29.791  92.3521  3050    10  5070     9  
2   1  18.0  3.24   5.832  10.4976  6260    19   770     4  
3   1  25.0  6.25  15.625  39.0625   420     1  6990    12  
4   1  22.0  4.84  10.648  23.4256  2015     6  9470    22  

[5 rows x 21 columns]

In [250]:

base1 = pd.read_csv( r'./data/base0.csv')
base1

Unnamed: 0       wage     lwage  sex  shs  hsg  scl  clg  ad  mw  ...  \
0             10   9.615385  2.263364    1    0    0    0    1   0   0  ...   
1             12  48.076923  3.872802    0    0    0    0    1   0   0  ...   
2             15  11.057692  2.403126    0    0    1    0    0   0   0  ...   
3             18  13.942308  2.634928    1    0    0    0    0   1   0  ...   
4             19  28.846154  3.361977    1    0    0    0    1   0   0  ...   
...          ...        ...       ...  ...  ...  ...  ...  ...  ..  ..  ...   
5145       32620  14.769231  2.692546    0    0    0    0    1   0   0  ...   
5146       32624  23.076923  3.138833    1    0    0    1    0   0   0  ...   
5147       32626  38.461538  3.649659    0    0    0    0    0   1   0  ...   
5148       32631  32.967033  3.495508    0    0    1    0    0   0   0  ...   
5149       32643  17.307692  2.851151    0    0    0    0    0   1   0  ...   

      we  ne  exp1  exp2    exp3     exp4     occ  occ2     ind  ind2  
0      0   1   7.0  0.49   0.343   0.2401  3600.0    11  8370.0    18  
1      0   1  31.0  9.61  29.791  92.3521  3050.0    10  5070.0     9  
2      0   1  18.0  3.24   5.832  10.4976  6260.0    19   770.0     4  
3      0   1  25.0  6.25  15.625  39.0625   420.0     1  6990.0    12  
4      0   1  22.0  4.84  10.648  23.4256  2015.0     6  9470.0    22  
...   ..  ..   ...   ...     ...      ...     ...   ...     ...   ...  
5145   1   0   9.0  0.81   0.729   0.6561  4700.0    16  4970.0     9  
5146   1   0  12.0  1.44   1.728   2.0736  4110.0    13  8680.0    20  
5147   1   0  11.0  1.21   1.331   1.4641  1550.0     4  3680.0     6  
5148   1   0  10.0  1.00   1.000   1.0000  2920.0     9  6570.0    11  
5149   1   0  14.0  1.96   2.744   3.8416  1610.0     5  7460.0    14  

[5150 rows x 21 columns]

In [303]:
base1.info()
#base1.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   salario  5150 non-null   float64
 1   lwage    5150 non-null   float64
 2   sex      5150 non-null   int64  
 3   exp1     5150 non-null   float64
 4   ind      5150 non-null   float64
dtypes: float64(4), int64(1)
memory usage: 201.3 KB


In [252]:
base1 = base1.rename( columns = { "wage":'salario', "Unnamed: 0":'id'}  )
base1

id    salario     lwage  sex  shs  hsg  scl  clg  ad  mw  ...  we  \
0        10   9.615385  2.263364    1    0    0    0    1   0   0  ...   0   
1        12  48.076923  3.872802    0    0    0    0    1   0   0  ...   0   
2        15  11.057692  2.403126    0    0    1    0    0   0   0  ...   0   
3        18  13.942308  2.634928    1    0    0    0    0   1   0  ...   0   
4        19  28.846154  3.361977    1    0    0    0    1   0   0  ...   0   
...     ...        ...       ...  ...  ...  ...  ...  ...  ..  ..  ...  ..   
5145  32620  14.769231  2.692546    0    0    0    0    1   0   0  ...   1   
5146  32624  23.076923  3.138833    1    0    0    1    0   0   0  ...   1   
5147  32626  38.461538  3.649659    0    0    0    0    0   1   0  ...   1   
5148  32631  32.967033  3.495508    0    0    1    0    0   0   0  ...   1   
5149  32643  17.307692  2.851151    0    0    0    0    0   1   0  ...   1   

      ne  exp1  exp2    exp3     exp4     occ  occ2     ind  ind2  
0      1   7.0  0.49   0.343   0.2401  3600.0    11  8370.0    18  
1      1  31.0  9.61  29.791  92.3521  3050.0    10  5070.0     9  
2      1  18.0  3.24   5.832  10.4976  6260.0    19   770.0     4  
3      1  25.0  6.25  15.625  39.0625   420.0     1  6990.0    12  
4      1  22.0  4.84  10.648  23.4256  2015.0     6  9470.0    22  
...   ..   ...   ...     ...      ...     ...   ...     ...   ...  
5145   0   9.0  0.81   0.729   0.6561  4700.0    16  4970.0     9  
5146   0  12.0  1.44   1.728   2.0736  4110.0    13  8680.0    20  
5147   0  11.0  1.21   1.331   1.4641  1550.0     4  3680.0     6  
5148   0  10.0  1.00   1.000   1.0000  2920.0     9  6570.0    11  
5149   0  14.0  1.96   2.744   3.8416  1610.0     5  7460.0    14  

[5150 rows x 21 columns]

In [253]:
base1 = base1.drop(["id","ind2"], axis=1)
base1
# axis 1 : columns
# axis 0 : rows

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1     48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

      exp2    exp3     exp4     occ  occ2     ind  
0     0.49   0.343   0.2401  3600.0    11  8370.0  
1     9.61  29.791  92.3521  3050.0    10  5070.0  
2     3.24   5.832  10.4976  6260.0    19   770.0  
3     6.25  15.625  39.0625   420.0     1  6990.0  
4     4.84  10.648  23.4256  2015.0     6  9470.0  
...    ...     ...      ...     ...   ...     ...  
5145  0.81   0.729   0.6561  4700.0    16  4970.0  
5146  1.44   1.728   2.0736  4110.0    13  8680.0  
5147  1.21   1.331   1.4641  1550.0     4  3680.0  
5148  1.00   1.000   1.0000  2920.0     9  6570.0  
5149  1.96   2.744   3.8416  1610.0     5  7460.0  

[5150 rows x 19 columns]

In [254]:
base1 = base1.drop(["we","exp2","exp3","exp4","occ","occ2","shs","hsg","scl","clg","ad","mw","so","ne"], axis=1)
base1

salario     lwage  sex  exp1     ind
0      9.615385  2.263364    1   7.0  8370.0
1     48.076923  3.872802    0  31.0  5070.0
2     11.057692  2.403126    0  18.0   770.0
3     13.942308  2.634928    1  25.0  6990.0
4     28.846154  3.361977    1  22.0  9470.0
...         ...       ...  ...   ...     ...
5145  14.769231  2.692546    0   9.0  4970.0
5146  23.076923  3.138833    1  12.0  8680.0
5147  38.461538  3.649659    0  11.0  3680.0
5148  32.967033  3.495508    0  10.0  6570.0
5149  17.307692  2.851151    0  14.0  7460.0

[5150 rows x 5 columns]

In [255]:
# row 1 and 3
base1.drop([1,3], axis = 0)

salario     lwage  sex  exp1     ind
0      9.615385  2.263364    1   7.0  8370.0
2     11.057692  2.403126    0  18.0   770.0
4     28.846154  3.361977    1  22.0  9470.0
5     11.730769  2.462215    1   1.0  7460.0
6     19.230769  2.956512    1  42.0  7280.0
...         ...       ...  ...   ...     ...
5145  14.769231  2.692546    0   9.0  4970.0
5146  23.076923  3.138833    1  12.0  8680.0
5147  38.461538  3.649659    0  11.0  3680.0
5148  32.967033  3.495508    0  10.0  6570.0
5149  17.307692  2.851151    0  14.0  7460.0

[5148 rows x 5 columns]

## Slicing  dataframe 

In [256]:
#select rows using positions
base1.iloc[0:6]

salario     lwage  sex  exp1     ind
0   9.615385  2.263364    1   7.0  8370.0
1  48.076923  3.872802    0  31.0  5070.0
2  11.057692  2.403126    0  18.0   770.0
3  13.942308  2.634928    1  25.0  6990.0
4  28.846154  3.361977    1  22.0  9470.0
5  11.730769  2.462215    1   1.0  7460.0

In [235]:
# row index and columns names 

base1.loc[:,['salario', 'lwage']]

salario     lwage
0      9.615385  2.263364
1     48.076923  3.872802
2     11.057692  2.403126
3     13.942308  2.634928
4     28.846154  3.361977
...         ...       ...
5145  14.769231  2.692546
5146  23.076923  3.138833
5147  38.461538  3.649659
5148  32.967033  3.495508
5149  17.307692  2.851151

[5150 rows x 2 columns]

In [236]:
base3 = base1[['lwage','salario']]

In [237]:
base3

lwage    salario
0     2.263364   9.615385
1     3.872802  48.076923
2     2.403126  11.057692
3     2.634928  13.942308
4     3.361977  28.846154
...        ...        ...
5145  2.692546  14.769231
5146  3.138833  23.076923
5147  3.649659  38.461538
5148  3.495508  32.967033
5149  2.851151  17.307692

[5150 rows x 2 columns]

In [196]:
#frame.loc[['one','two']] #selecion for labels 

#frame.iloc[0:2] #selection for numbers of rows

year  state  pop debt
one  2000   Lima  1.5  NaN
two  2001  Piura  1.7  NaN

In [238]:
base1[base1['sex']==1]

salario     lwage  sex  exp1   exp2     ind
0      9.615385  2.263364    1   7.0   0.49  8370.0
3     13.942308  2.634928    1  25.0   6.25  6990.0
4     28.846154  3.361977    1  22.0   4.84  9470.0
5     11.730769  2.462215    1   1.0   0.01  7460.0
6     19.230769  2.956512    1  42.0  17.64  7280.0
...         ...       ...  ...   ...    ...     ...
5137  13.461538  2.599837    1   8.0   0.64  8590.0
5138  19.711538  2.981204    1   8.0   0.64  8090.0
5140  45.546559  3.818735    1   5.0   0.25  8190.0
5143  24.038462  3.179655    1  17.0   2.89  9480.0
5146  23.076923  3.138833    1  12.0   1.44  8680.0

[2289 rows x 6 columns]

In [239]:
base1[base1.exp1 > 10].head(10)

salario     lwage  sex  exp1     exp2     ind
1   48.076923  3.872802    0  31.0   9.6100  5070.0
2   11.057692  2.403126    0  18.0   3.2400   770.0
3   13.942308  2.634928    1  25.0   6.2500  6990.0
4   28.846154  3.361977    1  22.0   4.8400  9470.0
6   19.230769  2.956512    1  42.0  17.6400  7280.0
7   19.230769  2.956512    0  37.0  13.6900  5680.0
8   12.000000  2.484907    1  31.0   9.6100  8590.0
11  12.019231  2.486508    0  30.0   9.0000  8270.0
13  13.461538  2.599837    1  20.5   4.2025  8190.0
14  16.346154  2.793993    1  25.0   6.2500  7870.0

In [240]:
base1[base1.exp1 < 5]

salario     lwage  sex  exp1    exp2     ind
5     11.730769  2.462215    1   1.0  0.0100  7460.0
9     19.230769  2.956512    1   4.0  0.1600  8190.0
17     8.653846  2.158004    0   3.5  0.1225   570.0
27    12.000000  2.484907    0   4.5  0.2025   770.0
30    42.307692  3.744969    1   0.0  0.0000  4795.0
...         ...       ...  ...   ...     ...     ...
5110  15.865385  2.764140    1   0.0  0.0000  8180.0
5114  18.750000  2.931194    1   2.0  0.0400  8370.0
5115  20.913462  3.040393    1   4.5  0.2025  8470.0
5118  12.019231  2.486508    0   4.0  0.1600  6170.0
5121  15.865385  2.764140    0   2.0  0.0400  7870.0

[1058 rows x 6 columns]

In [241]:
base1[(base1['sex']==1) & (base1.exp1 > 10) ].head(10) #and
#base1[(base1['sex']==1) | (base1.exp1 > 10) ].head(10) #or

salario     lwage  sex  exp1     exp2     ind
3   13.942308  2.634928    1  25.0   6.2500  6990.0
4   28.846154  3.361977    1  22.0   4.8400  9470.0
6   19.230769  2.956512    1  42.0  17.6400  7280.0
8   12.000000  2.484907    1  31.0   9.6100  8590.0
13  13.461538  2.599837    1  20.5   4.2025  8190.0
14  16.346154  2.793993    1  25.0   6.2500  7870.0
22  17.788462  2.878550    1  11.0   1.2100  7860.0
24  16.304348  2.791432    1  24.5   6.0025  5480.0
31  13.942308  2.634928    1  15.5   2.4025  4670.0
33  14.053254  2.642854    1  14.0   1.9600  7860.0

# If condition

Function **if** test conditions. 
- Equals: a == b
- Not Equals: a != b
- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b

<img src="https://www.dropbox.com/s/8xwqk2ze1116qvp/if-statement.jpg?dl=1" alt="image info" />

In [201]:
A = 20
B = 30

if A == B:
    print( 'Test expresion 1 is True' )
    
elif A > B:
    print( 'Test expresion 2 is True' )

elif A >= B:
    print( 'Test expresion 3 is True' )
    
elif A < B:
    print( 'Test expresion 4 is True' )
    
elif A <= B:
    print( 'Test expresion 5 is True' )
    
else:
    print( 'Test expresion 6 is True' )

Test expresion 4 is True


# For Loops

A for loop is used for iterating over a sequence. It has the following structure:

<img src="https://www.dropbox.com/s/a51fbr4m0vpvobe/for_loop.jpg?dl=1" alt="image info" />



In [147]:
secuencia = np.arange(1,20)
secuencia

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [150]:
secuencia = np.arange(1,20)

for i in secuencia:
    print("numero",i)


numero 1
numero 2
numero 3
numero 4
numero 5
numero 6
numero 7
numero 8
numero 9
numero 10
numero 11
numero 12
numero 13
numero 14
numero 15
numero 16
numero 17
numero 18
numero 19


In [156]:
productos = ["Laptop", "Celular", "Tablet", "Monitor"]
precios = [1200, 800, 500, 300]

for i in range(len(productos)):
    descuento = precios[i] * 0.10  # 10% de descuento
    nuevo_precio = precios[i] - descuento
    print(f"{productos[i]}: Precio original ${precios[i]}, con descuento ${nuevo_precio:.2f}")


Laptop: Precio original $1200, con descuento $1080.00
Celular: Precio original $800, con descuento $720.00
Tablet: Precio original $500, con descuento $450.00
Monitor: Precio original $300, con descuento $270.00


In [206]:
# Lista de estudiantes
students = ['Miguel', 'Anthony', 'Paul', 'Rodrigo', 'Jason']

# Lista de notas
grades = [16, 10, 14, 8, 12]  # Notas de los estudiantes

# Lista de semestres en los que se matricularon
semesters = ["2023-1", "2023-2", "2024-1", "2024-2", "2025-1"]

print("📜 Registro de Calificaciones:")
print("-" * 50)

# Recorrer las listas al mismo tiempo
for student, grade, sem in zip(students, grades, semesters):
    status = "🎉 ✅ Aprobó" if grade >= 11 else "❌ Reprobó"
    print(f"🧑‍🎓 {student} | Nota: {grade} | Semestre: {sem} | {status}")

print("-" * 50)
print("🎯 Para aprobar, se necesita una nota mínima de 11.")



📜 Registro de Calificaciones:
--------------------------------------------------
🧑‍🎓 Miguel | Nota: 16 | Semestre: 2018-1 | 🎉 ✅ Aprobó
🧑‍🎓 Anthony | Nota: 10 | Semestre: 2018-2 | ❌ Reprobó
🧑‍🎓 Paul | Nota: 14 | Semestre: 2019-1 | 🎉 ✅ Aprobó
🧑‍🎓 Rodrigo | Nota: 8 | Semestre: 2019-2 | ❌ Reprobó
🧑‍🎓 Jason | Nota: 12 | Semestre: 2020-1 | 🎉 ✅ Aprobó
--------------------------------------------------
🎯 Para aprobar, se necesita una nota mínima de 11.


# Functions

- `Arguments` − Elements that the function will use to make operations. Arguments are optional and can have default values.

- `Function Body` − This defines what your function does.
- `return` − Specifies the variable that will be the output of the function.

Return Value − The return value of a function is the last expression in the function body to be evaluated.
<br><br>
<font size="4">
<font color='green'>def</font> function_name <font color='green'>(arg_1, arg_2, ...) </font>:<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Function body <br>
    <br> &nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>return</font> result<br>
</font>

In [207]:
def suma(x, y):
    mate = (x + y)*15
    return mate

In [208]:
suma(10,4)

210

In [2]:
def calcular_descuento(precio, descuento):
    precio_final = precio - (precio * descuento / 100)
    return precio_final

producto = 150  # Precio en dólares
descuento = 10  # 10% de descuento

precio_con_descuento = calcular_descuento(producto, descuento)
print(f"El precio con descuento es: ${precio_con_descuento:.2f}")

El precio con descuento es: $135.00


In [5]:
def clasificar_cliente(gasto):
    """Clasifica un cliente según su gasto total."""
    if gasto > 1000:
        return "Cliente VIP"
    elif gasto >= 500:
        return "Cliente Regular"
    else:
        return "Cliente Nuevo"

# Lista de clientes con sus compras totales
clientes = [
    {"nombre": "Ana", "gasto": 1200},
    {"nombre": "Carlos", "gasto": 700},
    {"nombre": "Elena", "gasto": 300},
    {"nombre": "Luis", "gasto": 1500},
    {"nombre": "Marta", "gasto": 800}
]

# Clasificar clientes y mostrar resultados
for cliente in clientes:
    categoria = clasificar_cliente(cliente["gasto"])
    print(f"{cliente['nombre']} es un {categoria} (gastó ${cliente['gasto']}).")

Ana es un Cliente VIP (gastó $1200).
Carlos es un Cliente Regular (gastó $700).
Elena es un Cliente Nuevo (gastó $300).
Luis es un Cliente VIP (gastó $1500).
Marta es un Cliente Regular (gastó $800).


In [3]:
def clasificar_producto(nombre, ventas):
    """Clasifica un producto de Alicorp según sus ventas."""
    if ventas < 10000:
        categoria = "Baja"
    elif ventas <= 50000:     #más condiciones cuando if no es verdader
        categoria = "Media"
    else:                    #Ejecuta esto si no se cumplen las condiciones anteriores
        categoria = "Alta"

    return f"📦 El producto '{nombre}' tiene ventas {categoria} ({ventas} unidades)."

# Prueba con productos de Alicorp
productos = [
    ("Aceite Primor", 8000),
    ("Harina Blanca Flor", 30000),
    ("Galletas Casino", 70000)
]

for producto, ventas in productos:
    print(clasificar_producto(producto, ventas))


📦 El producto 'Aceite Primor' tiene ventas Baja (8000 unidades).
📦 El producto 'Harina Blanca Flor' tiene ventas Media (30000 unidades).
📦 El producto 'Galletas Casino' tiene ventas Alta (70000 unidades).


In [4]:
def es_rentable(toneladas, precio_por_tonelada, costo_operacional):
    """Determina si la extracción de cobre en Las Bambas es rentable."""
    ingresos = toneladas * precio_por_tonelada
    ganancia = ingresos - costo_operacional

    if ganancia > 0:
        return f"✅ Rentable: Ganancia de ${ganancia:,.2f}"
    else:
        return f"❌ No rentable: Pérdida de ${abs(ganancia):,.2f}"

# Prueba con valores de Las Bambas
toneladas_extraidas = 5000
precio_cobre = 9000  # Precio por tonelada en dólares
costo_operacional = 40000000  # Costos totales

resultado = es_rentable(toneladas_extraidas, precio_cobre, costo_operacional)
print(resultado)

✅ Rentable: Ganancia de $5,000,000.00
